package(default_visibility = ["//visibility:public"])
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_proto_library", "cc_test")

cc_library(
  name = "libsecp256k1",
  srcs = [
    "src/secp256k1.c",
    "src/precomputed_ecmult_gen.c",
  ],
  hdrs = [
    "include/secp256k1_ecdh.h",
    "include/secp256k1_extrakeys.h",
    "include/secp256k1.h",
    "include/secp256k1_preallocated.h",
    "include/secp256k1_recovery.h",
    "include/secp256k1_schnorrsig.h",
    "src/assumptions.h",
    'src/util.h',
    'src/field_impl.h',
    'src/field_5x52_impl.h',
    'src/field.h',
    'src/field_5x52.h',
    'src/modinv64_impl.h',
    'src/modinv64.h',
    'src/field_5x52_asm_impl.h',
    'src/scalar_impl.h',
    'src/scalar.h',
    'src/scalar_4x64.h',
    'src/scalar_4x64_impl.h',
    'src/group_impl.h',
    'src/group.h',
    'src/ecmult_impl.h',
    'src/ecmult.h',
    'src/scratch.h',
    'src/precomputed_ecmult.h',
    'src/ecmult_const_impl.h',
    'src/ecmult_const.h',
    'src/ecmult_gen_impl.h',
    'src/ecmult_gen.h',
    'src/hash_impl.h',
    'src/hash.h',
    'src/precomputed_ecmult_gen.h',
    'src/ecdsa_impl.h',
    'src/ecdsa.h',
    'src/eckey_impl.h',
    'src/eckey.h',
    'src/scratch_impl.h',
    'src/selftest.h',
    "src/libsecp256k1-config.h",
    "src/ecmult_gen_compute_table_impl.h",
    "src/ecmult_gen_compute_table.h",
  ],
  copts = [
    "-DHAVE_CONFIG_H",
  ],
);
